from . import base_shopify
from . import shopify_product
from . import product_template
from . import shopify_order
from . import res_config_setting
from . import shopify_cancel_order
from . import shopify_inventory
from . import shopify_stock_import
from . import shopify_customer
from . import shopify_log